#!/bin/bash

default_image="aquasec/trivy:0.29.2"
image="${BUILDKITE_PLUGIN_TRIVY_IMAGE:-$default_image}"

args=()

if [[ "${BUILDKITE_PLUGIN_TRIVY_EXIT_CODE:-0}" -eq 1 ]] ; then
  export args+=("--exit-code 1")
  echo "using exit-code=1 option while scanning"
else
  export args+=("--exit-code 0")
  echo "using exit-code=0 option while scanning"
fi

# if [[ "${BUILDKITE_PLUGIN_TRIVY_IGNORE_UNFIXED:-false}" -eq true ]] ; then
#   export args+=("--ignore-unfixed true")
# else
#   export args+=("--ignore-unfixed false")
# fi

if [[ -n "${BUILDKITE_PLUGIN_TRIVY_SEVERITY:-}" ]] ; then
  export args+=("--severity ${BUILDKITE_PLUGIN_TRIVY_SEVERITY}")
  echo "using non-default severity types"
fi
echo "scanning filesystem"
docker run -v $PWD:/workdir --rm $image fs ${args[@]} /workdir

if [[ -f $PWD/Dockerfile ]]; then
  docker build -t local/${BUILDKITE_PIPELINE_ID}:${BUILDKITE_COMMIT} .
  echo "scanning container image"
  docker run -v /var/run/docker.sock:/var/run/docker.sock --rm $image image ${args[@]} local/${BUILDKITE_PIPELINE_ID}:${BUILDKITE_COMMIT}
elif [[ ${BUILDKITE_TESTING} ]]; then
    cd $PWD/tests/testapp
    docker build -t local/${BUILDKITE_PIPELINE_ID}:${BUILDKITE_COMMIT} .
  echo "scanning container image"
  docker run -v /var/run/docker.sock:/var/run/docker.sock --rm $image image ${args[@]} local/${BUILDKITE_PIPELINE_ID}:${BUILDKITE_COMMIT} 
fi  
