#!/bin/bash

default_version="0.29.2"
version="${BUILDKITE_PLUGIN_TRIVY_VERSION:-$default_version}"
image="aquasec/trivy:${version}"

args=()
fsargs=()

if [[ "${BUILDKITE_PLUGIN_TRIVY_EXIT_CODE:-0}" -eq 1 ]] ; then
  args+=("--exit-code 1")
  echo "using exit-code=1 option while scanning"
else
  args+=("--exit-code 0")
  echo "using exit-code=0 option while scanning"
fi

# if [[ "${BUILDKITE_PLUGIN_TRIVY_IGNORE_UNFIXED:-false}" -eq true ]] ; then
#   export args+=("--ignore-unfixed true")
# else
#   export args+=("--ignore-unfixed false")
# fi

if [[ -n "${BUILDKITE_PLUGIN_TRIVY_SEVERITY:-}" ]] ; then
  args+=("--severity ${BUILDKITE_PLUGIN_TRIVY_SEVERITY}")
  echo "using non-default severity types"
fi

if [[ -n "${BUILDKITE_PLUGIN_TRIVY_SECURITY_CHECKS:-}" ]] ; then
  fsargs+=("--security-checks ${BUILDKITE_PLUGIN_TRIVY_SECURITY_CHECKS}")
  echo "using $BUILDKITE_PLUGIN_TRIVY_SECURITY_CHECKS security checks"
else
  echo "using default security checks"
  fsargs+=("--security-checks vuln,config")
fi

echo "scanning filesystem"
docker run -v "${PWD}":/workdir --rm "$image" fs "${args[@]}" "${fsargs[@]}" /workdir


if [[ -n "${BUILDKITE_PLUGIN_TRIVY_IMAGE_REF:-}" ]] ; then
  echo "using image from parameters"
  if [[ "${BUILDKITE_TESTING}" ]]; then
  	docker pull "${BUILDKITE_PLUGIN_TRIVY_IMAGE_REF}"
  fi
else
export BUILDKITE_PLUGIN_TRIVY_IMAGE_REF=local/"${BUILDKITE_PIPELINE_ID}":"${BUILDKITE_COMMIT}"
  if [[ -f $PWD/Dockerfile ]]; then
    docker build -t "${BUILDKITE_PLUGIN_TRIVY_IMAGE_REF}" .
  elif [[ ${BUILDKITE_TESTING} ]]; then
    cd "${PWD}"/tests/testapp || exit
    docker build -t "${BUILDKITE_PLUGIN_TRIVY_IMAGE_REF}" . 
  fi
fi

echo "scanning container image"
docker run -v /var/run/docker.sock:/var/run/docker.sock --rm "${image}" image "${args[@]}" "${BUILDKITE_PLUGIN_TRIVY_IMAGE_REF}"
